backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use common\models\Auth;
use common\models\User;
use Yii;
use yii\authclient\ClientInterface;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{
    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error', 'auth'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'oAuthSuccess'],
            ],
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logout action.
     *
     * @return string
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * This function will be triggered when user is successfuly authenticated using some oAuth client.
     *
     * @param ClientInterface $client
     * @return boolean|Response
     */
    public function oAuthSuccess($client) {
        // get user data from client

        $userAttributes = $client->getUserAttributes();

        $user = User::findByEmail($userAttributes["email"]);

        if ($user) {
            Yii::$app->user->login($user, 3600 * 24 * 30);
        } else {
            $user = new User();
            $user->email = $userAttributes["email"];
            $user->username = explode("@", $user->email)[0];
            $user->generatePasswordResetToken();
            $user->setPassword(rand(1000000, 100000000));
            $user->save();
        }

        $source = $client->getName();
        $sourceId = $userAttributes["id"];
        $uid = $user->id;
        $auth = Auth::find()->where([
            "user_id"=>$uid,
            "source"=>$source
        ])->one();

        if (!$auth) {
            $auth = new Auth();
        }

        $auth->user_id = $uid;
        $auth->source = $source;
        $auth->source_id = $sourceId;
        $auth->save();

        return $this->goHome();
    }

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use common\models\Auth;
use common\models\Feedback;
use common\models\News;
use common\models\Tags;
use common\models\Templates;
use common\models\User;
use frontend\models\SearchForm;
use frontend\models\TemplateGrapper;
use frontend\models\UserEditForm;
use phpDocumentor\Reflection\DocBlock\Tag;
use Yii;
use yii\authclient\ClientInterface;
use yii\base\InvalidParamException;
use yii\db\Expression;
use yii\helpers\ArrayHelper;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use common\models\LoginForm;
use frontend\models\PasswordResetRequestForm;
use frontend\models\ResetPasswordForm;
use frontend\models\SignupForm;
use frontend\models\ContactForm;
use yii\web\NotFoundHttpException;
use yii\web\Response;

/**
 * Site controller
 */
class SiteController extends Controller
{
    const EVENT_BEFORE_FEEDBACK_SAVE = "before_feedback_send";
    const EVENT_GET_FEED_MODEL = "get_feedback";

    /**
     * @var $feedModel Feedback
     */
    public $feedModel= null;


    public function init() {
        $this->on(self::EVENT_GET_FEED_MODEL, function() {
            Yii::$app->view->params['feedBackModel'] = $this->feedModel;
        });
        $this->on(self::EVENT_BEFORE_FEEDBACK_SAVE, function() {
            $model = new Feedback();

            if ($model->load(Yii::$app->request->post())) {
                if ($model->validate()) {
                    // form inputs are valid, do something here
                    $model->save();
                }
            }
            $this->feedModel = $model;
        });
    }



    /**
     * @inheritdoc
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout', 'signup'],
                'rules' => [
                    [
                        'actions' => ['signup'],
                        'allow' => true,
                        'roles' => ['?'],
                    ],
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @inheritdoc
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
            'auth' => [
                'class' => 'yii\authclient\AuthAction',
                'successCallback' => [$this, 'oAuthSuccess'],
            ],
        ];
    }

    /**
     * @param \yii\base\Action $event
     * @return bool
     * @throws BadRequestHttpException
     */
    public function beforeAction($event)
    {

        $this->trigger(self::EVENT_BEFORE_FEEDBACK_SAVE);
        if (!$this->feedModel->hasErrors() && !$this->feedModel->isNewRecord) {
            $this->refresh();
            return true;
        }

        return parent::beforeAction($event);
    }


    /**
     * Displays homepage.
     *
     * @return mixed
     */
    public function actionIndex()
    {
        $this->layout = "index";

        $news = News::find()->orderBy('updated_at desc, id asc')->limit(3)->all();


        return $this->render('index', ['news'=>$news]);
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionAbout()
    {
        return $this->render('about');
    }

    /**
     * Displays contact page.
     *
     * @return mixed
     */
    public function actionContact()
    {
        return $this->render('contact');
    }

    /**
     * Logs in a user.
     *
     * @return mixed
     */
    public function actionLogIn()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Logs out the current user.
     *
     * @return mixed
     */
    public function actionLogOut()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }


    /**
     * Signs user up.
     *
     * @return mixed
     */
    public function actionSignUp()
    {
        $model = new SignupForm();
        if ($model->load(Yii::$app->request->post())) {
            if ($user = $model->signup()) {
                if (Yii::$app->getUser()->login($user)) {
                    return $this->goHome();
                }
            }
        }

        return $this->render('signup', [
            'model' => $model,
        ]);
    }


    /**
     * Requests password reset.
     *
     * @return mixed
     */
    public function actionRequestPasswordReset()
    {
        $model = new PasswordResetRequestForm();
        if ($model->load(Yii::$app->request->post()) && $model->validate()) {
            if ($model->sendEmail()) {
                Yii::$app->session->setFlash('success', 'Check your email for further instructions.');

                return $this->goHome();
            } else {
                Yii::$app->session->setFlash('error', 'Sorry, we are unable to reset password for the provided email address.');
            }
        }

        return $this->render('requestPasswordResetToken', [
            'model' => $model,
        ]);
    }

    /**
     * Resets password.
     *
     * @param string $token
     * @return mixed
     * @throws BadRequestHttpException
     */
    public function actionResetPassword($token)
    {
        try {
            $model = new ResetPasswordForm($token);
        } catch (InvalidParamException $e) {
            throw new BadRequestHttpException($e->getMessage());
        }

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->resetPassword()) {
            Yii::$app->session->setFlash('success', 'New password saved.');

            return $this->goHome();
        }

        return $this->render('resetPassword', [
            'model' => $model,
        ]);
    }

    /**
     * This function will be triggered when user is successfuly authenticated using some oAuth client.
     *
     * @param ClientInterface $client
     * @return boolean|Response
     */
    public function oAuthSuccess($client) {
        // get user data from client

        $userAttributes = $client->getUserAttributes();

        $user = User::findByEmail($userAttributes["email"]);

        if ($user) {
            Yii::$app->user->login($user, 3600 * 24 * 30);
        } else {
            $user = new User();
            $user->email = $userAttributes["email"];
            $user->username = explode("@", $user->email)[0];
            $user->generatePasswordResetToken();
            $user->setPassword(rand(1000000, 100000000));
            $user->save();
        }

        $source = $client->getName();
        $sourceId = $userAttributes["id"];
        $uid = $user->id;
        $auth = Auth::find()->where([
            "user_id"=>$uid,
            "source"=>$source
        ])->one();

        if (!$auth) {
            $auth = new Auth();
        }

        $auth->user_id = $uid;
        $auth->source = $source;
        $auth->source_id = $sourceId;
        $auth->save();

        return $this->goHome();
    }


    function actionArticle($id) {
        $article = News::findOne(["id"=>$id]);
        $article->views++;
        $article->save();

        if (!$article) {
            throw new NotFoundHttpException();
        }
        return $this->render('article', ["article"=>$article]);
    }


    function actionNews() {

        return $this->render('news');
    }

    function actionSearch() {

        $model = new SearchForm();

        $renderLoader = false;
        $model->loadData();
        $model->strict = false;
        if (strlen($model->query)) {
            $renderLoader = true;
        }

        return $this->render('search', ["model"=>$model, 'renderLoader'=>$renderLoader]);
    }


    function actionTags($tag=null) {

        $model = new SearchForm();
        $model->loadData();


        $renderLoader = false;
        if ($tag) {
            $model->tags = $tag;
            $renderLoader = true;
        }

        $randomTags = Tags::find()
            ->orderBy(new Expression('rand()'))
            ->limit(30)->all();

        return $this->render('tags', ["model"=>$model,
            'renderLoader'=>$renderLoader,
            'tag' => $tag,
            'tags'=>$randomTags] );
    }


    function actionRender4News($start) {
        $query = Yii::$app->request->get('query', '');
        $sites = Yii::$app->request->get('sites', '');
        $tags = Yii::$app->request->get('tags', '');
        $strict = Yii::$app->request->get('strict', false);


        $news = SearchForm::search($start, 4, $query, $sites, $tags, $strict);
        return json_encode([
            "content"=>$this->renderPartial('parts/news4', ['news'=>$news, 'start'=>$start]),
            "count"=>sizeof($news),
            ]);
    }


    function actionRender3News($start) {

        $query = Yii::$app->request->get('query', '');
        $sites = Yii::$app->request->get('tags', '');
        $tags = Yii::$app->request->get('sites', '');
        $strict = Yii::$app->request->get('strict', true);


        $news = SearchForm::search($start, 3, $query, $sites, $tags, $strict);

        if (!$news) {

frontend/views/site/parts/news3.php
<?php
/**
 * @var $news \common\models\News[]
 * @var $start string
 * @var $this \yii\web\View
 */

$id = 0;
?>
<?php if (!sizeof($news)): ?>
    <div class="article-no-more">
        <h1 class="icon-note"><?= $start?Yii::t("news", "article_no_more"):Yii::t("news", "article_no_news")?></h1>
    </div>

<?php else: ?>
<?php foreach ($news as $article): ?>
    <?php $url = \yii\helpers\Url::to(["site/article", "id"=>$article->id]);?>
    <?php switch(++$id): ?><?php case 1:?>
                <!-- Contact List -->
                <div class="section-seperator margin-b-0 news-block-1">
                    <div class="container" >
                        <div class="row">

                            <!-- Contact List -->
                            <div class="col-sm-8 col-sm-12 col-lg-6 col-lg-offset-3">
                                <div class="news-modal-1">
                                    <h3><a href="<?= $url?>"><?= $article->title?></a> <span class="text-uppercase margin-l-20"><?= Yii::t("main", "lang_".$article->lang)?></span> <span class="pull-right icon-calendar"> <?= date("h:i d.m.Y", $article->updated_at)?></span></h3>
                                    <div style="margin-top: -15px;"><?php foreach($article->getTagsAsArray() as $source): ?> <a href="<?= \yii\helpers\Url::to(["site/tags", "tag"=>$source])?>"><span class="icon-tag"></span> <?= $source?></a><?php endforeach?></div>
                                    <p><?= Yii::t("main","source_s")?>:&nbsp;&nbsp;<?php foreach($article->getSitesAsArray() as $source): ?> <a href="<?=$source?>"><span class="icon-anchor"></span> <?= $source?></a><?php endforeach?></p>
                                    <p class="text-justify" style="min-height:70px">
                                        <img class="pull-left" style="margin:0 10px 10px 0;" alt="<?= $article->title?>" src="<?=$article->pic?>" height="80px"/>
                                        <?= $article->short?>
                                    </p>
                                    <div class="text-right">
                                        <a class="btn btn-warning text-uppercase" href="<?= $url?>"><?= Yii::t("main", "read")?></a>
                                    </div>
                                </div>
                            </div>
                            <!-- End Contact List -->

                        </div>
                        <!--// end row -->
                    </div>
                </div>
                <!-- End Contact List -->

                <?php break;?>
                <?php case 2:?>

                <!-- Promo Section -->
                <div class="promo-section overflow-h">
                    <div class="container">
                        <div class="clearfix">
                            <div class="ver-center">
                                <div class="ver-center-aligned">
                                    <div class="promo-section-col">

                                        <h3><a href="<?= $url?>"><?= $article->title?></a> <span class="text-uppercase margin-l-20"><?= Yii::t("main", "lang_".$article->lang)?></span></h3>
                                        <div style="margin-top: -15px;"><?php foreach($article->getTagsAsArray() as $source): ?> <a href="<?= \yii\helpers\Url::to(["site/tags", "tag"=>$source])?>"><span class="icon-tag"></span> <?= $source?></a><?php endforeach?></div>


                                        <p><?= Yii::t("main","source_s")?>:&nbsp;&nbsp;<?php foreach($article->getSitesAsArray() as $source): ?> <a href="<?=$source?>"><span class="icon-anchor"></span> <?= $source?></a><?php endforeach?></p>

                                        <p class="text-justify" style="min-height:70px">
                                            <img class="pull-left" style="margin:0 10px 10px 0;" alt="<?= $article->title?>" src="<?=$article->pic?>" height="80px"/>
                                            <?= $article->short?>
                                        </p>
                                        <div class="text-right">
                                            <span class="icon-calendar pull-left" style="margin-top:10px"> <?= date("h:i d.m.Y", $article->updated_at)?></span>
                                            <a class="btn btn-warning text-uppercase" href="<?= $url?>"><?= Yii::t("main", "read")?></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                <!-- End Promo Section -->
                <?php break;?>
                <?php case 3:?>

                    <div class="promo-section-img-right">
                        <div style="position: relative;"><div style="position: absolute; padding:10%; left:0; top:0;">

                                <div class="news-modal-1">
                                    <h3><a href="<?= $url?>"><?= $article->title?></a> <span class="text-uppercase margin-l-20"><?= Yii::t("main", "lang_".$article->lang)?></span> <span class="pull-right icon-calendar"> <?= date("h:i d.m.Y", $article->updated_at)?></span></h3>
                                    <div style="margin-top: -15px;"><?php foreach($article->getTagsAsArray() as $source): ?> <a href="<?= \yii\helpers\Url::to(["site/tags", "tag"=>$source])?>"><span class="icon-tag"></span> <?= $source?></a><?php endforeach?></div>
                                    <p><?= Yii::t("main","source_s")?>:&nbsp;&nbsp;<?php foreach($article->getSitesAsArray() as $source): ?> <a href="<?=$source?>"><span class="icon-anchor"></span> <?= $source?></a><?php endforeach?></p>
                                    <p class="text-justify" style="min-height:70px">
                                        <img class="pull-left" style="margin:0 10px 10px 0;" alt="<?= $article->title?>" src="<?=$article->pic?>" height="80px"/>
                                        <?= $article->short?>
                                    </p>
                                    <div class="text-right">
                                        <a class="btn btn-warning text-uppercase" href="<?= $url?>"><?= Yii::t("main", "read")?></a>
                                    </div>
                                </div>
                            </div></div>
                        <img class="img-responsive" src="/img/970x970/01.jpg" alt="Content Image" />

                    </div>
                </div>
                <?php break;?>

    <?php endswitch;?>
<?php endforeach;?>

<?php endif; ?>

<?php if (sizeof($news) == 2):?>
    </div>
<?php endif; ?>

frontend/views/site/parts/news4.php
<?php
/**
 * @var $news \common\models\News[]
 * @var $this \yii\web\View
 * @var $start string
 */

$id = 2;
?>
<?php if (!sizeof($news)): ?>
    <div class="article-no-more">
        <h1 class="icon-note"><?= $start?Yii::t("news", "article_no_more"):Yii::t("news", "article_no_news")?></h1>
    </div>

<?php else: ?>
<div class="row" style="margin:15px;">
    <?php foreach ($news as $article): ?>
        <?php
            $url = \yii\helpers\Url::to(["site/article", "id"=>$article->id]);
            $id++;
            ?>
        <div class="col-md-6 search-article-block-col">

                    <div class="search-article-block">
                        <h3><a href="<?= $url?>"><?= $article->title?></a> <span class="text-uppercase margin-l-20"><?= Yii::t("main", "lang_".$article->lang)?></span> <span class="pull-right icon-calendar"> <?= date("h:i d.m.Y", $article->updated_at)?></span></h3>
                        <div style="margin: -15px 0 15px 0;"><?php foreach($article->getTagsAsArray() as $source): ?> <a href="<?= \yii\helpers\Url::to(["site/tags", "tag"=>$source])?>"><span class="icon-tag"></span> <?= $source?></a><?php endforeach?></div>
                        <p><?= Yii::t("main","source_s")?>:&nbsp;&nbsp;<?php foreach($article->getSitesAsArray() as $source): ?> <a href="<?=$source?>"><span class="icon-anchor"></span> <?= $source?></a><?php endforeach?></p>
                        <p class="text-justify" style="min-height:70px">
                            <img class="pull-left" style="margin:0 10px 10px 0;" alt="<?= $article->title?>" src="<?=$article->pic?>" height="80px"/>
                            <?= $article->short?>
                        </p>
                        <div class="text-right">
                            <a class="btn btn-warning text-uppercase" href="<?= $url?>"><?= Yii::t("main", "read")?></a>
                        </div>
                    </div>
        </div>
    <?php endforeach;?>
</div>

<?php endif; ?>

frontend/views/site/parts/userEdit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;

/* @var $this yii\web\View */
/* @var $model \common\models\User */
/* @var $form ActiveForm */
?>
<div class="UserEdit container" style="max-width: 400px">

    <?php $form = ActiveForm::begin(); ?>

        <?= $form->field($model, 'username') ?>

        <?= $form->field($model, 'password')->passwordInput() ?>

        <div class="form-group">
            <?= Html::submitButton(Yii::t('main', 'save'), ['class' => 'btn btn-primary']) ?>
        </div>
    <?php ActiveForm::end(); ?>

</div><!-- UserEdit -->